name: GCH

description: 9 turbines (3x3 grid) with Gaussian-Curl-Hybrid wake model

floris_version: v4

logging:
  console:
    enable: true
    level: WARNING
  file:
    enable: false
    level: WARNING

solver:
  type: turbine_grid
  turbine_grid_points: 3

farm:
  layout_x: [0, 500, 1000, 0, 500, 1000, 0, 500, 1000]
  layout_y: [0, 0, 0, 500, 500, 500, 1000, 1000, 1000]

  turbine_type:
  - nrel_5MW

flow_field:
  air_density: 1.225
  reference_wind_height: -1
  turbulence_intensities: [0.1]
  wind_directions: [270.0]
  wind_shear: 0.12  
  wind_speeds: [8.0]
  wind_veer: 0.0

wake:
  model_strings:
    combination_model: sosfs
    deflection_model: gauss
    turbulence_model: crespo_hernandez
    velocity_model: gauss

  enable_secondary_steering: true
  enable_yaw_added_recovery: true
  enable_active_wake_mixing: false
  enable_transverse_velocities: true

  wake_deflection_parameters:
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004

  wake_velocity_parameters:
    gauss:
      alpha: 0.58
      beta: 0.077
      ka: 0.38
      kb: 0.004

  wake_turbulence_parameters:
    crespo_hernandez:
      initial: 0.1
      constant: 0.5
      ai: 0.8
      downstream: -0.32
